### ISSUE TITLE
Create post

### ISSUE THREAD

**Issue by rgnarok** [Anupriyabanger/NeeleshMisra_Community#7]
<img width="705" alt="image" src="https://github.com/Anupriyabanger/NeeleshMisra_Community/assets/85341053/0f7ac2d2-b153-428b-9948-da40a8c0102e">

- Icons are not visible like a cross
- Remove post to connections as admin will be by default connected to everyone and so the post will be shared with everyone 
- Remove the term byte and make it post as it is discussed with the client

**Comment by vayuzpriya** [comment]
![image](https://github.com/Anupriyabanger/NeeleshMisra_Community/assets/81085431/faf68270-4c6c-4c83-81ce-5aa06c4ad0ca)
icon visible

**Comment by vayuzpriya** [comment]
- [x] Icons are not visible like a cross
- [ ] Remove post to connections as admin will be by default connected to everyone and so the post will be shared with everyone
- [x] Remove the term byte and make it post as it is discussed with the client
